### ISSUE TITLE
Не працює видалення в Групуванні

### ISSUE THREAD

**Issue by AndriyNesterenya** [new-era-uk/New.Era#18]
Неможливо видалити пункт в Групуванні.

**Comment by alex-kukhtin** [comment]
Done

**Comment by AndriyNesterenya** [comment]
З кнопки Х видаляє.
З меню по лівому кліку - нічого не відбувається (редагування і створення працює). 
![image](https://user-images.githubusercontent.com/38098758/167386712-49a6f9d8-92a1-473f-95af-7941ca2de42c.png)
