### ISSUE TITLE
При Группировании товаров использовать 2-е служебные группировки: "Без группировки" и "Не распределенные"

### ISSUE THREAD

**Issue by ViperGSV** [new-era-uk/New.Era#20]
При группировке товаров хотелось бы иметь 2-е служебные группировки:
- Без группировки - уже есть и отображает все товары справочника
- Не распределенные - товары для которых не выбрана ни одна их групп, т.е. подлежащие распределению

**Comment by alex-kukhtin** [comment]
Done
