### ISSUE TITLE
В стартовій конфігурації заповнити  довідник стандартних одиниць виміру

### ISSUE THREAD

**Issue by AndriyNesterenya** [new-era-uk/New.Era#3]
Наприклад:

- Літр, л, 0138  
- Кілограм, кг, 0301
- Грам, г, 0303
- Тонна, т, 0306 
- Центнер, цт, 0311
- Метр, м, 0101 
- Квадратний метр, кв.м, 0123  
- Кубічний метр, куб.м, 0134
- Погонний метр, пог.м, 2702 
- Штука, шт, 2009 
- Пара, п, 1617
- Рулон, рул, 2116

**Comment by alex-kukhtin** [comment]
Додана можливість додавати те, що потрібно з каталогу.
![image](https://user-images.githubusercontent.com/26379138/163975334-a452c400-32b3-4423-9e5f-f300220c18a9.png)
