### ISSUE TITLE
Неможливо створити контрагента з діалогу вибору в Закупівлях/Продажах

### ISSUE THREAD

**Issue by AndriyNesterenya** [new-era-uk/New.Era#4]
Неможливо створити контрагента з діалогу вибору в Закупівлях/Продажах

![image](https://user-images.githubusercontent.com/38098758/164176860-32194d71-b9f4-4902-bc8b-6d01c492c225.png)

**Comment by AndriyNesterenya** [comment]
Те саме - в діалогах вибору Склада і Підприємства

**Comment by alex-kukhtin** [comment]
Ну уж підприємство точно не нужно "на лету" создавать.

**Comment by alex-kukhtin** [comment]
Зроблено
