### ISSUE TITLE
Створення елементів довідників в місті потреби в них

### ISSUE THREAD

**Issue by Svitelsky** [new-era-uk/New.Era#5]
Реалізувати можливість створення елементів довідників (контрагент, номенклатурна позиція) з мінімальним набором реквізитів (назва) з місця, де виникає потреба в ньому (в документі в списку вибору).

Тобто коли при стовренні документа з'ясовується що потрібної позиції немає у списку, то має бути можливість там же її стоврити не полишаючи документ, що стоврюється.

**Comment by alex-kukhtin** [comment]
Зроблено
