### ISSUE TITLE
Об'єднати стартові SQL-скрипти в один

### ISSUE THREAD

**Issue by AndriyNesterenya** [new-era-uk/New.Era#6]
Для зменшення кількості помилок при встановленні системи непідготованим користувачем пропоную об'єднувати скрипти \New.Era.App\App_application\@sql\platform\a2v10platform.sql та \New.Era\New.Era.App\App_application\SqlScripts\application.sql в один.
Це виключить зайві помилки при порушенні порядку виконання скриптів.

**Comment by alex-kukhtin** [comment]
Done. Остался только application.sql
